ATTACH DATABASE "C:\Users\jorda\Documents\GitHub\DE-Tech-Interview\staging.db" AS STAGING;
ATTACH DATABASE "C:\Users\jorda\Documents\GitHub\DE-Tech-Interview\foundation.db" AS FOUNDATION;

INSERT INTO TARGET 
    (TARGET_ID,
     APPROVEDSYMBOL,
     BIOTYPE,
     DW_DISEASE_ID)
SELECT 
    T.ID, 
    T.APPROVEDSYMBOL,
    T.BIOTYPE,
    DA.DW_DISEASE_ID
FROM STAGING.TARGETS T
LEFT JOIN STAGING.DIRECTASSOCIATION DA ON DA.TARGET_ID = D.ID
LEFT JOIN FOUNDATION.DISEASES D ON DA.DISEASE_ID = D.DISEASE_ID