ATTACH DATABASE "C:\Users\jorda\Documents\GitHub\DE-Tech-Interview\staging.db" AS STAGING;
ATTACH DATABASE "C:\Users\jorda\Documents\GitHub\DE-Tech-Interview\foundation.db" AS FOUNDATION;

-- INSERT INTO TARGET 
--     (TARGET_ID,
--      APPROVEDSYMBOL,
--      BIOTYPE,
--      DW_DISEASE_ID)
SELECT 
    T.ID, 
    T.APPROVEDSYMBOL,
    T.BIOTYPE,
    D.DW_DISEASE_ID
FROM STAGING.TARGETS T
LEFT JOIN STAGING.DIRECTASSOCIATION DA ON DA.TARGETID = T.ID
LEFT JOIN FOUNDATION.DISEASE D ON DA.DISEASEID = D.DISEASE_ID;

SELECT * FROM 