ATTACH DATABASE "C:\Users\jorda\Documents\GitHub\DE-Tech-Interview\staging.db" AS STAGING;

INSERT INTO DIRECT_ASSOCIATION  
    (DISEASE_ID,
    TARGET_ID,
    SCORE,
    EVIDENCE_COUNT)
SELECT 
    D.DISEASEID, 
    D.TARGETID,
    D.SCORE,
    D.EVIDENCECOUNT
FROM STAGING.DIRECTASSOCIATION D;