CREATE TABLE TARGET (
    DW_TARGET_ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    TARGET_ID            VARCHAR(500) NOT NULL,
    APPROVEDSYMBOL       VARCHAR(500),
    BIOTYPE              VARCHAR(500),
    DW_DISEASE_ID        INTEGER,
    FOREIGN KEY (DW_DISEASE_ID) REFERENCES DISEASE (DW_DISEASE_ID)
);