CREATE TABLE UNIPROT (
    DW_UNIPROT_ID               INTEGER PRIMARY KEY AUTOINCREMENT,
    DW_DISEASES_ID              FOREIGN KEY,
    DW_PROTEINS_ID              FOREIGN KEY,
    DW_TARGETS_ID               FOREIGN KEY,
    PRIMARY_ACCESSION           VARCHAR(500),
    RECOMMENDED_PROTEIN_NAME    VARCHAR(500),
    SPECIES_COMMON_NAME         VARCHAR(500),
    SEQUENCE_LENGTH             INTEGER,
    PRIMARY_GENE_NAME           VARCHAR(500)   

);