CREATE TABLE UNIPROT (
    DW_UNIPROT_ID               INTEGER PRIMARY KEY AUTOINCREMENT,
    DW_DISEASE_ID              INTEGER,
    DW_PROTEIN_ID              INTEGER,
    DW_TARGET_ID               INTEGER,
    PRIMARY_ACCESSION           VARCHAR(500),
    RECOMMENDED_PROTEIN_NAME    VARCHAR(500),
    SPECIES_COMMON_NAME         VARCHAR(500),
    SEQUENCE_LENGTH             INTEGER,
    PRIMARY_GENE_NAME           VARCHAR(500),
    FOREIGN KEY (DW_DISEASE_ID) REFERENCES DISEASE (DW_DISEASE_ID)
    FOREIGN KEY (DW_PROTEIN_ID) REFERENCES DISEASE (DW_PROTEIN_ID)
    FOREIGN KEY (DW_TARGET_ID) REFERENCES DISEASE (DW_TARGET_ID)
);