INSERT INTO PROTEIN  
    (PROTEIN_1,
     PROTEIN_2, 
     COMBINED_SCORE)
SELECT 
    S.PROTEIN1, 
    S.PROTEIN2,
    S.COMBINED_SCORE
FROM STRING S
WHERE PROTEIN1 IS NOT NULL
    AND PROTEIN2 IS NOT NULL;