ATTACH DATABASE "C:\Users\jorda\Documents\GitHub\DE-Tech-Interview\foundation.db" AS FOUNDATION;

CREATE VIEW UNIPROT_ASSOCIATIONS AS 
SELECT 
    U.RECOMMENDED_PROTEIN_NAME  AS UP_PROTEIN_NAME,
    P.PROTEIN_2                 AS ASSOCIATED_PROTEIN_NAME,
    D.DISEASE_NAME              AS ASSOCIATED_DISEASES
FROM FOUNDATION.UNIPROT U 
LEFT JOIN FOUNDATION.PROTEIN P ON P.DW_PROTEIN_ID = U.DW_PROTEIN_ID
LEFT JOIN FOUNDATION.DISEASES D ON D.DW_DISEASE_ID = U.DW_DISEASE_ID 
WHERE P.COMBINED_SCORE > 200; 